CREATE TABLE "MEMBER" (
		"MEMBER_NO"	NUMBER		NOT NULL,
		"MEMBER_ID"	NVARCHAR2(100)		NOT NULL,
		"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
		"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
		"MEMBER_EMAIL"	NVARCHAR2(30)		NOT NULL,
		"MEMBER_ADDRESS"	NVARCHAR2(100)		NULL,
		"MEMBER_TEL"	CHAR(13)		NULL,
    "PROFILE_IMG" VARCHAR2(255),
    "ENROLL_DATE" DATE DEFAULT SYSDATE,
    "MEMBER_DEL_FL" CHAR(1) DEFAULT 'N',
    "AUTHORITY" NUMBER DEFAULT 1,
    "NAVER_LOGIN" CHAR(1) DEFAULT 'N'
);


ALTER TABLE MEMBER
ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO);

SELECT * FROM MEMBER;


CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', 'API연습', 'user01@kh.com', 
				NULL, '010-1234-1234', NULL, DEFAULT,DEFAULT,DEFAULT);

COMMIT;


SELECT MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_EMAIL, MEMBER_NICKNAME,
MEMBER_TEL, MEMBER_ADDRESS, PROFILE_IMG, AUTHORITY,
TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE
FROM "MEMBER"
WHERE MEMBER_ID = 'user01'
AND MEMBER_DEL_FL = 'N';


SELECT COUNT(*)
FROM "MEMBER"
WHERE MEMBER_EMAIL = 'user01@kh.com'
AND MEMBER_DEL_FL = 'N';

ALTER TABLE MEMBER ADD NAVER_LOGIN CHAR(1) DEFAULT 'N';

ALTER TABLE MEMBER ADD SOCIAL_LOGIN_TYPE CHAR(1) DEFAULT 'D' NOT NULL;

ALTER TABLE MEMBER DROP COLUMN NAVER_LOGIN;

UPDATE "MEMBER" SET 
MEMBER_DEL_FL = 'Y'
WHERE NAVER_LOGIN = 'Y';

COMMIT;


DELETE FROM "MEMBER" WHERE MEMBER_NO = 9;